export type FiatSeedItem = {
  code: string;
  rank: number;
  name: string;
  decimals: number;
};

export const FIAT_TOP100: FiatSeedItem[] = [
  { code: 'USD', rank: 1, name: 'US Dollar', decimals: 2 },
  { code: 'EUR', rank: 2, name: 'Euro', decimals: 2 },
  { code: 'JPY', rank: 3, name: 'Japanese Yen', decimals: 0 },
  { code: 'GBP', rank: 4, name: 'British Pound Sterling', decimals: 2 },
  { code: 'CHF', rank: 5, name: 'Swiss Franc', decimals: 2 },
  { code: 'CAD', rank: 6, name: 'Canadian Dollar', decimals: 2 },
  { code: 'AUD', rank: 7, name: 'Australian Dollar', decimals: 2 },
  { code: 'CNY', rank: 8, name: 'Chinese Yuan', decimals: 2 },
  { code: 'HKD', rank: 9, name: 'Hong Kong Dollar', decimals: 2 },
  { code: 'SGD', rank: 10, name: 'Singapore Dollar', decimals: 2 },
  { code: 'SEK', rank: 11, name: 'Swedish Krona', decimals: 2 },
  { code: 'NOK', rank: 12, name: 'Norwegian Krone', decimals: 2 },
  { code: 'DKK', rank: 13, name: 'Danish Krone', decimals: 2 },
  { code: 'NZD', rank: 14, name: 'New Zealand Dollar', decimals: 2 },
  { code: 'KRW', rank: 15, name: 'South Korean Won', decimals: 0 },
  { code: 'INR', rank: 16, name: 'Indian Rupee', decimals: 2 },
  { code: 'BRL', rank: 17, name: 'Brazilian Real', decimals: 2 },
  { code: 'MXN', rank: 18, name: 'Mexican Peso', decimals: 2 },
  { code: 'ZAR', rank: 19, name: 'South African Rand', decimals: 2 },
  { code: 'AED', rank: 20, name: 'UAE Dirham', decimals: 2 },
  { code: 'SAR', rank: 21, name: 'Saudi Riyal', decimals: 2 },
  { code: 'PLN', rank: 22, name: 'Polish Zloty', decimals: 2 },
  { code: 'TRY', rank: 23, name: 'Turkish Lira', decimals: 2 },
  { code: 'THB', rank: 24, name: 'Thai Baht', decimals: 2 },
  { code: 'IDR', rank: 25, name: 'Indonesian Rupiah', decimals: 2 },
  { code: 'TWD', rank: 26, name: 'New Taiwan Dollar', decimals: 2 },
  { code: 'CZK', rank: 27, name: 'Czech Koruna', decimals: 2 },
  { code: 'HUF', rank: 28, name: 'Hungarian Forint', decimals: 2 },
  { code: 'ILS', rank: 29, name: 'Israeli New Shekel', decimals: 2 },
  { code: 'MYR', rank: 30, name: 'Malaysian Ringgit', decimals: 2 },
  { code: 'PHP', rank: 31, name: 'Philippine Peso', decimals: 2 },
  { code: 'CLP', rank: 32, name: 'Chilean Peso', decimals: 0 },
  { code: 'COP', rank: 33, name: 'Colombian Peso', decimals: 2 },
  { code: 'ARS', rank: 34, name: 'Argentine Peso', decimals: 2 },
  { code: 'PEN', rank: 35, name: 'Peruvian Sol', decimals: 2 },
  { code: 'RON', rank: 36, name: 'Romanian Leu', decimals: 2 },
  { code: 'BGN', rank: 37, name: 'Bulgarian Lev', decimals: 2 },
  { code: 'RSD', rank: 38, name: 'Serbian Dinar', decimals: 2 },
  { code: 'UAH', rank: 39, name: 'Ukrainian Hryvnia', decimals: 2 },
  { code: 'KZT', rank: 40, name: 'Kazakhstani Tenge', decimals: 2 },
  { code: 'QAR', rank: 41, name: 'Qatari Riyal', decimals: 2 },
  { code: 'KWD', rank: 42, name: 'Kuwaiti Dinar', decimals: 3 },
  { code: 'BHD', rank: 43, name: 'Bahraini Dinar', decimals: 3 },
  { code: 'OMR', rank: 44, name: 'Omani Rial', decimals: 3 },
  { code: 'JOD', rank: 45, name: 'Jordanian Dinar', decimals: 3 },
  { code: 'EGP', rank: 46, name: 'Egyptian Pound', decimals: 2 },
  { code: 'MAD', rank: 47, name: 'Moroccan Dirham', decimals: 2 },
  { code: 'NGN', rank: 48, name: 'Nigerian Naira', decimals: 2 },
  { code: 'KES', rank: 49, name: 'Kenyan Shilling', decimals: 2 },
  { code: 'GHS', rank: 50, name: 'Ghanaian Cedi', decimals: 2 },
  { code: 'PKR', rank: 51, name: 'Pakistani Rupee', decimals: 2 },
  { code: 'BDT', rank: 52, name: 'Bangladeshi Taka', decimals: 2 },
  { code: 'LKR', rank: 53, name: 'Sri Lankan Rupee', decimals: 2 },
  { code: 'VND', rank: 54, name: 'Vietnamese Dong', decimals: 0 },
  { code: 'RUB', rank: 55, name: 'Russian Ruble', decimals: 2 },
  { code: 'BYN', rank: 56, name: 'Belarusian Ruble', decimals: 2 },
  { code: 'GEL', rank: 57, name: 'Georgian Lari', decimals: 2 },
  { code: 'AMD', rank: 58, name: 'Armenian Dram', decimals: 2 },
  { code: 'AZN', rank: 59, name: 'Azerbaijani Manat', decimals: 2 },
  { code: 'UZS', rank: 60, name: 'Uzbekistani Som', decimals: 2 },
  { code: 'TJS', rank: 61, name: 'Tajikistani Somoni', decimals: 2 },
  { code: 'KGS', rank: 62, name: 'Kyrgyzstani Som', decimals: 2 },
  { code: 'MNT', rank: 63, name: 'Mongolian Tugrik', decimals: 2 },
  { code: 'ISK', rank: 64, name: 'Icelandic Krona', decimals: 0 },
  { code: 'FJD', rank: 65, name: 'Fijian Dollar', decimals: 2 },
  { code: 'XPF', rank: 66, name: 'CFP Franc', decimals: 0 },
  { code: 'XOF', rank: 67, name: 'West African CFA Franc', decimals: 0 },
  { code: 'XAF', rank: 68, name: 'Central African CFA Franc', decimals: 0 },
  { code: 'DZD', rank: 69, name: 'Algerian Dinar', decimals: 2 },
  { code: 'TND', rank: 70, name: 'Tunisian Dinar', decimals: 3 },
  { code: 'BWP', rank: 71, name: 'Botswana Pula', decimals: 2 },
  { code: 'MUR', rank: 72, name: 'Mauritian Rupee', decimals: 2 },
  { code: 'NAD', rank: 73, name: 'Namibian Dollar', decimals: 2 },
  { code: 'ETB', rank: 74, name: 'Ethiopian Birr', decimals: 2 },
  { code: 'UGX', rank: 75, name: 'Ugandan Shilling', decimals: 0 },
  { code: 'TZS', rank: 76, name: 'Tanzanian Shilling', decimals: 2 },
  { code: 'RWF', rank: 77, name: 'Rwandan Franc', decimals: 0 },
  { code: 'BIF', rank: 78, name: 'Burundian Franc', decimals: 0 },
  { code: 'ZMW', rank: 79, name: 'Zambian Kwacha', decimals: 2 },
  { code: 'MWK', rank: 80, name: 'Malawian Kwacha', decimals: 2 },
  { code: 'MZN', rank: 81, name: 'Mozambican Metical', decimals: 2 },
  { code: 'AOA', rank: 82, name: 'Angolan Kwanza', decimals: 2 },
  { code: 'XCD', rank: 83, name: 'East Caribbean Dollar', decimals: 2 },
  { code: 'BBD', rank: 84, name: 'Barbadian Dollar', decimals: 2 },
  { code: 'JMD', rank: 85, name: 'Jamaican Dollar', decimals: 2 },
  { code: 'TTD', rank: 86, name: 'Trinidad and Tobago Dollar', decimals: 2 },
  { code: 'GTQ', rank: 87, name: 'Guatemalan Quetzal', decimals: 2 },
  { code: 'HNL', rank: 88, name: 'Honduran Lempira', decimals: 2 },
  { code: 'NIO', rank: 89, name: 'Nicaraguan Cordoba', decimals: 2 },
  { code: 'CRC', rank: 90, name: 'Costa Rican Colon', decimals: 2 },
  { code: 'DOP', rank: 91, name: 'Dominican Peso', decimals: 2 },
  { code: 'PAB', rank: 92, name: 'Panamanian Balboa', decimals: 2 },
  { code: 'UYU', rank: 93, name: 'Uruguayan Peso', decimals: 2 },
  { code: 'PYG', rank: 94, name: 'Paraguayan Guarani', decimals: 0 },
  { code: 'BOB', rank: 95, name: 'Bolivian Boliviano', decimals: 2 },
  { code: 'SVC', rank: 96, name: 'Salvadoran Colon', decimals: 2 },
  { code: 'BAM', rank: 97, name: 'Bosnia-Herzegovina Convertible Mark', decimals: 2 },
  { code: 'ALL', rank: 98, name: 'Albanian Lek', decimals: 2 },
  { code: 'MKD', rank: 99, name: 'Macedonian Denar', decimals: 2 },
  { code: 'MDL', rank: 100, name: 'Moldovan Leu', decimals: 2 },
];
